= 10 ways to get super-productive with Spring Boot

This sample project is going to be used for a talk demoing how Spring Boot helps
you to be super-productive.

== Scenario

=== Schema update

Let's improve our `Speaker` entity so that we list the `github` account. It's very
simple really but using Flyway allows us to make sure the schema is upgraded
automatically on startup. Adding Flyway and putting the script at a default location
is enough.

=== Switch to a different database

It is very easy to create a `application-local.properties` configuration file and
point to a different database. In this example, we chose to deploy our app using MySQL
instead of the embedded H2 database.

`application-local.properties` can be ignored in `.gitignore` and only kept locally.

=== OAuth authentication

We want to use OAuth to allow a speaker or an administrator to login. We do so by
adding the security starter and Spring's Oauth2 support.

A simple `SecurityConfig` defines the permissions for the various endpoints: to make
things a little bit more easier, we redirect all actuator endpoints to `/admin`. We
can reuse our `local` profile to provide the `client-id` and `client-secret` of an
application that binds to `localhost:8080`. Of course the target environment should
provide a _real_ secret.

=== Custom configuration

In our previous steps, we've hardcoded the list of github users that have admin
rights. This is fine for our demo but it would be nice if we would be able to
configure that the same way we can configure Spring Boot.

`@ConfigurationProperties` allows us to create our own pojo and adding
`spring-boot-configuration-processor` to our build generates the relevant meta-data
that the IDEs use to offer auto-completion.

=== Caching

Our `GithubClient` is retrieving the invited speakers using the Github API and
we may suffer from a rate limit quite quickly. To avoid that, we can cache the
result of those calls.

It's super easy to do that, just add `@EnableCaching` to your app and annotate
your bean methods. This gives a very basic cache store using `ConcurrentHashMaps`. The
drawback of such store is that it does not offer any feature with regards to
expiration and memory consumption. But we can just as easily switch to a different
store if needed.

For instance we could use `JSR-107` (`JCache`). It is as easy as adding the cache
api and a compliant JSR-107 provider. Once you have that you can configure your caches
with the library-specific infrastructure or via a `JCacheManagerCustomizer`.

=== Adding useful info automatically

Spring Boot 1.4 allows you to add all kinds of information to your `/info` endpoint
easily. We can for example fetch build and git related information. It is possible
to customize that information and use build-specific variables.